# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'realtimeitem.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(760, 569)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(22, 14, 293, 541))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(14, 22, 273, 506))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_cm_fut_price = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cm_fut_price.setFont(font)
        self.checkBox_cm_fut_price.setObjectName("checkBox_cm_fut_price")
        self.verticalLayout.addWidget(self.checkBox_cm_fut_price)
        self.checkBox_cm_fut_quote = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cm_fut_quote.setFont(font)
        self.checkBox_cm_fut_quote.setObjectName("checkBox_cm_fut_quote")
        self.verticalLayout.addWidget(self.checkBox_cm_fut_quote)
        self.checkBox_cm_opt_price = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cm_opt_price.setFont(font)
        self.checkBox_cm_opt_price.setObjectName("checkBox_cm_opt_price")
        self.verticalLayout.addWidget(self.checkBox_cm_opt_price)
        self.checkBox_cm_opt_price_1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cm_opt_price_1.setFont(font)
        self.checkBox_cm_opt_price_1.setObjectName("checkBox_cm_opt_price_1")
        self.verticalLayout.addWidget(self.checkBox_cm_opt_price_1)
        self.checkBox_cm_opt_quote = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cm_opt_quote.setFont(font)
        self.checkBox_cm_opt_quote.setObjectName("checkBox_cm_opt_quote")
        self.verticalLayout.addWidget(self.checkBox_cm_opt_quote)
        self.checkBox_cm_opt_quote_1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_cm_opt_quote_1.setFont(font)
        self.checkBox_cm_opt_quote_1.setObjectName("checkBox_cm_opt_quote_1")
        self.verticalLayout.addWidget(self.checkBox_cm_opt_quote_1)
        self.checkBox_nm_fut_price = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nm_fut_price.setFont(font)
        self.checkBox_nm_fut_price.setObjectName("checkBox_nm_fut_price")
        self.verticalLayout.addWidget(self.checkBox_nm_fut_price)
        self.checkBox_nm_fut_quote = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nm_fut_quote.setFont(font)
        self.checkBox_nm_fut_quote.setObjectName("checkBox_nm_fut_quote")
        self.verticalLayout.addWidget(self.checkBox_nm_fut_quote)
        self.checkBox_nm_opt_price = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nm_opt_price.setFont(font)
        self.checkBox_nm_opt_price.setObjectName("checkBox_nm_opt_price")
        self.verticalLayout.addWidget(self.checkBox_nm_opt_price)
        self.checkBox_nm_opt_price_1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nm_opt_price_1.setFont(font)
        self.checkBox_nm_opt_price_1.setObjectName("checkBox_nm_opt_price_1")
        self.verticalLayout.addWidget(self.checkBox_nm_opt_price_1)
        self.checkBox_nm_opt_quote = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nm_opt_quote.setFont(font)
        self.checkBox_nm_opt_quote.setObjectName("checkBox_nm_opt_quote")
        self.verticalLayout.addWidget(self.checkBox_nm_opt_quote)
        self.checkBox_nm_opt_quote_1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nm_opt_quote_1.setFont(font)
        self.checkBox_nm_opt_quote_1.setObjectName("checkBox_nm_opt_quote_1")
        self.verticalLayout.addWidget(self.checkBox_nm_opt_quote_1)
        self.checkBox_kospi_kosdaq = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_kospi_kosdaq.setFont(font)
        self.checkBox_kospi_kosdaq.setObjectName("checkBox_kospi_kosdaq")
        self.verticalLayout.addWidget(self.checkBox_kospi_kosdaq)
        self.checkBox_supply_demand = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_supply_demand.setFont(font)
        self.checkBox_supply_demand.setObjectName("checkBox_supply_demand")
        self.verticalLayout.addWidget(self.checkBox_supply_demand)
        self.checkBox_news = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_news.setFont(font)
        self.checkBox_news.setObjectName("checkBox_news")
        self.verticalLayout.addWidget(self.checkBox_news)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_sp500 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_sp500.setFont(font)
        self.checkBox_sp500.setObjectName("checkBox_sp500")
        self.horizontalLayout_5.addWidget(self.checkBox_sp500)
        self.checkBox_dow = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_dow.setFont(font)
        self.checkBox_dow.setObjectName("checkBox_dow")
        self.horizontalLayout_5.addWidget(self.checkBox_dow)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_nasdaq = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nasdaq.setFont(font)
        self.checkBox_nasdaq.setObjectName("checkBox_nasdaq")
        self.horizontalLayout_6.addWidget(self.checkBox_nasdaq)
        self.checkBox_hangseng = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_hangseng.setFont(font)
        self.checkBox_hangseng.setObjectName("checkBox_hangseng")
        self.horizontalLayout_6.addWidget(self.checkBox_hangseng)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_oil = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_oil.setFont(font)
        self.checkBox_oil.setObjectName("checkBox_oil")
        self.horizontalLayout_7.addWidget(self.checkBox_oil)
        self.checkBox_gold = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_gold.setFont(font)
        self.checkBox_gold.setObjectName("checkBox_gold")
        self.horizontalLayout_7.addWidget(self.checkBox_gold)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_eurofx = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_eurofx.setFont(font)
        self.checkBox_eurofx.setObjectName("checkBox_eurofx")
        self.horizontalLayout_8.addWidget(self.checkBox_eurofx)
        self.checkBox_yen = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_yen.setFont(font)
        self.checkBox_yen.setObjectName("checkBox_yen")
        self.horizontalLayout_8.addWidget(self.checkBox_yen)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_adi = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_adi.setFont(font)
        self.checkBox_adi.setObjectName("checkBox_adi")
        self.horizontalLayout_9.addWidget(self.checkBox_adi)
        self.checkBox_reserved1 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_reserved1.setFont(font)
        self.checkBox_reserved1.setObjectName("checkBox_reserved1")
        self.horizontalLayout_9.addWidget(self.checkBox_reserved1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(338, 114, 399, 57))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(14, 22, 369, 21))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.lineEdit_bb_period = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_bb_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bb_period.setObjectName("lineEdit_bb_period")
        self.horizontalLayout_12.addWidget(self.lineEdit_bb_period)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.lineEdit_bb_1st_std = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_bb_1st_std.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bb_1st_std.setObjectName("lineEdit_bb_1st_std")
        self.horizontalLayout_12.addWidget(self.lineEdit_bb_1st_std)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.lineEdit_bb_2nd_std = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_bb_2nd_std.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bb_2nd_std.setObjectName("lineEdit_bb_2nd_std")
        self.horizontalLayout_12.addWidget(self.lineEdit_bb_2nd_std)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(338, 14, 399, 89))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(12, 22, 371, 52))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_call_itm = QtWidgets.QLabel(self.layoutWidget3)
        self.label_call_itm.setObjectName("label_call_itm")
        self.horizontalLayout_4.addWidget(self.label_call_itm)
        self.spinBox_call_itm = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_call_itm.setObjectName("spinBox_call_itm")
        self.horizontalLayout_4.addWidget(self.spinBox_call_itm)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_call_otm = QtWidgets.QLabel(self.layoutWidget3)
        self.label_call_otm.setObjectName("label_call_otm")
        self.horizontalLayout_4.addWidget(self.label_call_otm)
        self.spinBox_call_otm = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_call_otm.setObjectName("spinBox_call_otm")
        self.horizontalLayout_4.addWidget(self.spinBox_call_otm)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_put_itm = QtWidgets.QLabel(self.layoutWidget3)
        self.label_put_itm.setObjectName("label_put_itm")
        self.horizontalLayout_3.addWidget(self.label_put_itm)
        self.spinBox_put_itm = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_put_itm.setObjectName("spinBox_put_itm")
        self.horizontalLayout_3.addWidget(self.spinBox_put_itm)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_put_otm = QtWidgets.QLabel(self.layoutWidget3)
        self.label_put_otm.setObjectName("label_put_otm")
        self.horizontalLayout_3.addWidget(self.label_put_otm)
        self.spinBox_put_otm = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_put_otm.setObjectName("spinBox_put_otm")
        self.horizontalLayout_3.addWidget(self.spinBox_put_otm)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(338, 352, 399, 203))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(12, 25, 373, 48))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_periodic_plot = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_periodic_plot.setObjectName("checkBox_periodic_plot")
        self.verticalLayout_7.addWidget(self.checkBox_periodic_plot)
        self.checkBox_plot_sync = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_plot_sync.setObjectName("checkBox_plot_sync")
        self.verticalLayout_7.addWidget(self.checkBox_plot_sync)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_telegram = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_telegram.setObjectName("checkBox_telegram")
        self.verticalLayout_3.addWidget(self.checkBox_telegram)
        self.checkBox_tts = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkBox_tts.setObjectName("checkBox_tts")
        self.verticalLayout_3.addWidget(self.checkBox_tts)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(12, 81, 373, 21))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.lineEdit_drate_ratio = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_drate_ratio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_drate_ratio.setObjectName("lineEdit_drate_ratio")
        self.horizontalLayout.addWidget(self.lineEdit_drate_ratio)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22)
        self.lineEdit_drate_offset = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_drate_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_drate_offset.setObjectName("lineEdit_drate_offset")
        self.horizontalLayout.addWidget(self.lineEdit_drate_offset)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget6.setGeometry(QtCore.QRect(12, 112, 373, 21))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.lineEdit_tolerance = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_tolerance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tolerance.setObjectName("lineEdit_tolerance")
        self.horizontalLayout_14.addWidget(self.lineEdit_tolerance)
        self.horizontalLayout_14.setStretch(0, 10)
        self.horizontalLayout_14.setStretch(1, 2)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget7.setGeometry(QtCore.QRect(12, 144, 373, 21))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.lineEdit_plot = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_plot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_plot.setObjectName("lineEdit_plot")
        self.horizontalLayout_15.addWidget(self.lineEdit_plot)
        self.horizontalLayout_15.setStretch(0, 10)
        self.horizontalLayout_15.setStretch(1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(338, 182, 399, 83))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget8.setGeometry(QtCore.QRect(14, 20, 369, 21))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.lineEdit_rsi_period = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_rsi_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rsi_period.setObjectName("lineEdit_rsi_period")
        self.horizontalLayout_2.addWidget(self.lineEdit_rsi_period)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.lineEdit_rsi_offset = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_rsi_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rsi_offset.setObjectName("lineEdit_rsi_offset")
        self.horizontalLayout_2.addWidget(self.lineEdit_rsi_offset)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.lineEdit_rsi_scale_factor = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_rsi_scale_factor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rsi_scale_factor.setObjectName("lineEdit_rsi_scale_factor")
        self.horizontalLayout_2.addWidget(self.lineEdit_rsi_scale_factor)
        self.widget = QtWidgets.QWidget(self.groupBox_5)
        self.widget.setGeometry(QtCore.QRect(14, 51, 369, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.lineEdit_cci1_period = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_cci1_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_cci1_period.setObjectName("lineEdit_cci1_period")
        self.horizontalLayout_13.addWidget(self.lineEdit_cci1_period)
        self.label_21 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.lineEdit_cci2_period = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_cci2_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_cci2_period.setObjectName("lineEdit_cci2_period")
        self.horizontalLayout_13.addWidget(self.lineEdit_cci2_period)
        self.label_23 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.lineEdit_ssl_period = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_ssl_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ssl_period.setObjectName("lineEdit_ssl_period")
        self.horizontalLayout_13.addWidget(self.lineEdit_ssl_period)
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(338, 280, 399, 59))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.checkBox_lagging_span = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_lagging_span.setGeometry(QtCore.QRect(314, -2, 69, 19))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_lagging_span.setFont(font)
        self.checkBox_lagging_span.setObjectName("checkBox_lagging_span")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_2.setGeometry(QtCore.QRect(12, 24, 373, 21))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.lineEdit_ichimoku_baseline_period = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_ichimoku_baseline_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ichimoku_baseline_period.setObjectName("lineEdit_ichimoku_baseline_period")
        self.horizontalLayout_11.addWidget(self.lineEdit_ichimoku_baseline_period)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.lineEdit_ichimoku_conversionline_period = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_ichimoku_conversionline_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ichimoku_conversionline_period.setObjectName("lineEdit_ichimoku_conversionline_period")
        self.horizontalLayout_11.addWidget(self.lineEdit_ichimoku_conversionline_period)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.lineEdit_ichimoku_span_period = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_ichimoku_span_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ichimoku_span_period.setObjectName("lineEdit_ichimoku_span_period")
        self.horizontalLayout_11.addWidget(self.lineEdit_ichimoku_span_period)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "실시간 설정"))
        self.groupBox.setTitle(_translate("Dialog", "Real Time Request Item"))
        self.checkBox_cm_fut_price.setText(_translate("Dialog", "본월물 선물가격"))
        self.checkBox_cm_fut_quote.setText(_translate("Dialog", "본월물 선물호가"))
        self.checkBox_cm_opt_price.setText(_translate("Dialog", "본월물 옵션가격(전체)"))
        self.checkBox_cm_opt_price_1.setText(_translate("Dialog", "본월물 옵션가격"))
        self.checkBox_cm_opt_quote.setText(_translate("Dialog", "본월물 옵션호가(전체)"))
        self.checkBox_cm_opt_quote_1.setText(_translate("Dialog", "본월물 옵션호가"))
        self.checkBox_nm_fut_price.setText(_translate("Dialog", "차월물 선물가격"))
        self.checkBox_nm_fut_quote.setText(_translate("Dialog", "차월물 선물호가"))
        self.checkBox_nm_opt_price.setText(_translate("Dialog", "차월물 옵션가격(전체)"))
        self.checkBox_nm_opt_price_1.setText(_translate("Dialog", "차월물 옵션가격"))
        self.checkBox_nm_opt_quote.setText(_translate("Dialog", "차월물 옵션호가(전체)"))
        self.checkBox_nm_opt_quote_1.setText(_translate("Dialog", "차월물 옵션호가"))
        self.checkBox_kospi_kosdaq.setText(_translate("Dialog", "KOSPI/KOSDAQ 지수"))
        self.checkBox_supply_demand.setText(_translate("Dialog", "투자자별 매매현황"))
        self.checkBox_news.setText(_translate("Dialog", "NEWS"))
        self.checkBox_sp500.setText(_translate("Dialog", "S&&P 500"))
        self.checkBox_dow.setText(_translate("Dialog", "DOW"))
        self.checkBox_nasdaq.setText(_translate("Dialog", "NASDAQ"))
        self.checkBox_hangseng.setText(_translate("Dialog", "HANGSENG"))
        self.checkBox_oil.setText(_translate("Dialog", "WTI OIL"))
        self.checkBox_gold.setText(_translate("Dialog", "GOLD"))
        self.checkBox_eurofx.setText(_translate("Dialog", "EUROFX"))
        self.checkBox_yen.setText(_translate("Dialog", "YEN"))
        self.checkBox_adi.setText(_translate("Dialog", "ADI"))
        self.checkBox_reserved1.setText(_translate("Dialog", "Reserved"))
        self.groupBox_2.setTitle(_translate("Dialog", "Double Bollinger Bands (이평주기, 1st STD, 2nd STD)"))
        self.label_5.setText(_translate("Dialog", "주기"))
        self.label_3.setText(_translate("Dialog", "1st"))
        self.label_4.setText(_translate("Dialog", "2nd"))
        self.groupBox_3.setTitle(_translate("Dialog", "ITM, OTM Setting"))
        self.label_call_itm.setText(_translate("Dialog", "콜내가"))
        self.label_call_otm.setText(_translate("Dialog", "콜외가"))
        self.label_put_itm.setText(_translate("Dialog", "풋내가"))
        self.label_put_otm.setText(_translate("Dialog", "풋외가"))
        self.groupBox_4.setTitle(_translate("Dialog", "User Switch"))
        self.checkBox_periodic_plot.setText(_translate("Dialog", "Option Table Periodic Update"))
        self.checkBox_plot_sync.setText(_translate("Dialog", "Plot Sync"))
        self.checkBox_telegram.setText(_translate("Dialog", "Telegram"))
        self.checkBox_tts.setText(_translate("Dialog", "TTS"))
        self.label_18.setText(_translate("Dialog", "선물 vs SP500 등락율비"))
        self.label_22.setText(_translate("Dialog", "Drate Offset"))
        self.label_19.setText(_translate("Dialog", "실시간수신 허용오차(초)"))
        self.label_20.setText(_translate("Dialog", "Plot 갱신주기(msec)"))
        self.groupBox_5.setTitle(_translate("Dialog", "RSI 주기, OFFET, SCALE && CCI 1/2 주기 && SSL 주기"))
        self.label_10.setText(_translate("Dialog", "RSI 주기"))
        self.label_11.setText(_translate("Dialog", "OFFSET"))
        self.label_14.setText(_translate("Dialog", "SCALE"))
        self.label_17.setText(_translate("Dialog", "CCI1 주기"))
        self.label_21.setText(_translate("Dialog", "CCI2 주기"))
        self.label_23.setText(_translate("Dialog", "SSL 주기"))
        self.groupBox_6.setTitle(_translate("Dialog", "One Eye Balance Indicator"))
        self.checkBox_lagging_span.setText(_translate("Dialog", "후행스팬"))
        self.label_12.setText(_translate("Dialog", "기준선 주기"))
        self.label_13.setText(_translate("Dialog", "전환선 주기"))
        self.label_15.setText(_translate("Dialog", "SPAN 주기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

