# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_board.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1912, 1020)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.tableWidget_put = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_put.setGeometry(QtCore.QRect(966, 60, 940, 940))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_put.setFont(font)
        self.tableWidget_put.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_put.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_put.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_put.setLineWidth(1)
        self.tableWidget_put.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_put.setObjectName("tableWidget_put")
        self.tableWidget_put.setColumnCount(0)
        self.tableWidget_put.setRowCount(0)
        self.tableWidget_call = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_call.setGeometry(QtCore.QRect(13, 60, 940, 610))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_call.setFont(font)
        self.tableWidget_call.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_call.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_call.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_call.setLineWidth(1)
        self.tableWidget_call.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_call.setObjectName("tableWidget_call")
        self.tableWidget_call.setColumnCount(0)
        self.tableWidget_call.setRowCount(0)
        self.tableWidget_fut = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_fut.setGeometry(QtCore.QRect(13, 682, 940, 138))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_fut.setFont(font)
        self.tableWidget_fut.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_fut.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_fut.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_fut.setObjectName("tableWidget_fut")
        self.tableWidget_fut.setColumnCount(0)
        self.tableWidget_fut.setRowCount(0)
        self.tableWidget_supply = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_supply.setGeometry(QtCore.QRect(488, 922, 465, 78))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.tableWidget_supply.setFont(font)
        self.tableWidget_supply.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_supply.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_supply.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_supply.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_supply.setObjectName("tableWidget_supply")
        self.tableWidget_supply.setColumnCount(0)
        self.tableWidget_supply.setRowCount(0)
        self.tableWidget_quote = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_quote.setGeometry(QtCore.QRect(13, 832, 941, 79))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_quote.setFont(font)
        self.tableWidget_quote.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_quote.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_quote.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget_quote.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_quote.setObjectName("tableWidget_quote")
        self.tableWidget_quote.setColumnCount(0)
        self.tableWidget_quote.setRowCount(0)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(13, 922, 466, 78))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 20, 1891, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_main_time = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_main_time.setFont(font)
        self.label_main_time.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_main_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_main_time.setObjectName("label_main_time")
        self.horizontalLayout.addWidget(self.label_main_time)
        self.label_atm = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_atm.setFont(font)
        self.label_atm.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_atm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_atm.setObjectName("label_atm")
        self.horizontalLayout.addWidget(self.label_atm)
        self.label_1st_index = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_1st_index.setFont(font)
        self.label_1st_index.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_1st_index.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_1st_index.setObjectName("label_1st_index")
        self.horizontalLayout.addWidget(self.label_1st_index)
        self.label_2nd_index = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2nd_index.setFont(font)
        self.label_2nd_index.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2nd_index.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2nd_index.setObjectName("label_2nd_index")
        self.horizontalLayout.addWidget(self.label_2nd_index)
        self.label_3rd_index = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3rd_index.setFont(font)
        self.label_3rd_index.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3rd_index.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3rd_index.setObjectName("label_3rd_index")
        self.horizontalLayout.addWidget(self.label_3rd_index)
        self.label_4th_index = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4th_index.setFont(font)
        self.label_4th_index.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4th_index.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4th_index.setObjectName("label_4th_index")
        self.horizontalLayout.addWidget(self.label_4th_index)
        self.label_kospi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_kospi.setFont(font)
        self.label_kospi.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_kospi.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_kospi.setObjectName("label_kospi")
        self.horizontalLayout.addWidget(self.label_kospi)
        self.label_kosdaq = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_kosdaq.setFont(font)
        self.label_kosdaq.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_kosdaq.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_kosdaq.setObjectName("label_kosdaq")
        self.horizontalLayout.addWidget(self.label_kosdaq)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_start = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_start.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.pushButton_telegram = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_telegram.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_telegram.setFont(font)
        self.pushButton_telegram.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_telegram.setCheckable(True)
        self.pushButton_telegram.setObjectName("pushButton_telegram")
        self.horizontalLayout.addWidget(self.pushButton_telegram)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "선물옵션 전광판"))
        self.label_main_time.setText(_translate("Dialog", "Message Notification !!!"))
        self.label_atm.setText(_translate("Dialog", "양합/양차"))
        self.label_1st_index.setText(_translate("Dialog", "1st index"))
        self.label_2nd_index.setText(_translate("Dialog", "2nd index"))
        self.label_3rd_index.setText(_translate("Dialog", "3rd index"))
        self.label_4th_index.setText(_translate("Dialog", "4th index"))
        self.label_kospi.setText(_translate("Dialog", "KOSPI"))
        self.label_kosdaq.setText(_translate("Dialog", "KOSDAQ"))
        self.pushButton_start.setText(_translate("Dialog", "Start"))
        self.pushButton_telegram.setText(_translate("Dialog", "Telegram"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
