# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skybot.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 681)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/skybot_cm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 6, 622, 411))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 28, 595, 369))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1st = QtWidgets.QLabel(self.layoutWidget)
        self.label_1st.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1st.setObjectName("label_1st")
        self.verticalLayout.addWidget(self.label_1st)
        self.label_2nd = QtWidgets.QLabel(self.layoutWidget)
        self.label_2nd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2nd.setObjectName("label_2nd")
        self.verticalLayout.addWidget(self.label_2nd)
        self.label_3rd = QtWidgets.QLabel(self.layoutWidget)
        self.label_3rd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3rd.setObjectName("label_3rd")
        self.verticalLayout.addWidget(self.label_3rd)
        self.label_4th = QtWidgets.QLabel(self.layoutWidget)
        self.label_4th.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4th.setObjectName("label_4th")
        self.verticalLayout.addWidget(self.label_4th)
        self.label_5th = QtWidgets.QLabel(self.layoutWidget)
        self.label_5th.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5th.setObjectName("label_5th")
        self.verticalLayout.addWidget(self.label_5th)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout.addWidget(self.pushButton_reset)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(8, 428, 623, 157))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(17, 32, 591, 110))
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_sp500 = QtWidgets.QLabel(self.widget)
        self.label_sp500.setObjectName("label_sp500")
        self.horizontalLayout_5.addWidget(self.label_sp500)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_sp500_low = QtWidgets.QLabel(self.widget)
        self.label_sp500_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sp500_low.setObjectName("label_sp500_low")
        self.horizontalLayout_5.addWidget(self.label_sp500_low)
        self.label_sp500_high = QtWidgets.QLabel(self.widget)
        self.label_sp500_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sp500_high.setObjectName("label_sp500_high")
        self.horizontalLayout_5.addWidget(self.label_sp500_high)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_nasdaq = QtWidgets.QLabel(self.widget)
        self.label_nasdaq.setObjectName("label_nasdaq")
        self.horizontalLayout_4.addWidget(self.label_nasdaq)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_nasdaq_low = QtWidgets.QLabel(self.widget)
        self.label_nasdaq_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nasdaq_low.setObjectName("label_nasdaq_low")
        self.horizontalLayout_4.addWidget(self.label_nasdaq_low)
        self.label_nasdaq_high = QtWidgets.QLabel(self.widget)
        self.label_nasdaq_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nasdaq_high.setObjectName("label_nasdaq_high")
        self.horizontalLayout_4.addWidget(self.label_nasdaq_high)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_wti = QtWidgets.QLabel(self.widget)
        self.label_wti.setObjectName("label_wti")
        self.horizontalLayout_3.addWidget(self.label_wti)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_wti_low = QtWidgets.QLabel(self.widget)
        self.label_wti_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wti_low.setObjectName("label_wti_low")
        self.horizontalLayout_3.addWidget(self.label_wti_low)
        self.label_wti_high = QtWidgets.QLabel(self.widget)
        self.label_wti_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wti_high.setObjectName("label_wti_high")
        self.horizontalLayout_3.addWidget(self.label_wti_high)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_euro = QtWidgets.QLabel(self.widget)
        self.label_euro.setObjectName("label_euro")
        self.horizontalLayout_2.addWidget(self.label_euro)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_euro_low = QtWidgets.QLabel(self.widget)
        self.label_euro_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_euro_low.setObjectName("label_euro_low")
        self.horizontalLayout_2.addWidget(self.label_euro_low)
        self.label_euro_high = QtWidgets.QLabel(self.widget)
        self.label_euro_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_euro_high.setObjectName("label_euro_high")
        self.horizontalLayout_2.addWidget(self.label_euro_high)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_dow = QtWidgets.QLabel(self.widget)
        self.label_dow.setObjectName("label_dow")
        self.horizontalLayout_9.addWidget(self.label_dow)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.label_dow_low = QtWidgets.QLabel(self.widget)
        self.label_dow_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dow_low.setObjectName("label_dow_low")
        self.horizontalLayout_9.addWidget(self.label_dow_low)
        self.label_dow_high = QtWidgets.QLabel(self.widget)
        self.label_dow_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dow_high.setObjectName("label_dow_high")
        self.horizontalLayout_9.addWidget(self.label_dow_high)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_hsi = QtWidgets.QLabel(self.widget)
        self.label_hsi.setObjectName("label_hsi")
        self.horizontalLayout_8.addWidget(self.label_hsi)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.label_hsi_low = QtWidgets.QLabel(self.widget)
        self.label_hsi_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hsi_low.setObjectName("label_hsi_low")
        self.horizontalLayout_8.addWidget(self.label_hsi_low)
        self.label_hsi_high = QtWidgets.QLabel(self.widget)
        self.label_hsi_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hsi_high.setObjectName("label_hsi_high")
        self.horizontalLayout_8.addWidget(self.label_hsi_high)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_gold = QtWidgets.QLabel(self.widget)
        self.label_gold.setObjectName("label_gold")
        self.horizontalLayout_7.addWidget(self.label_gold)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.label_gold_low = QtWidgets.QLabel(self.widget)
        self.label_gold_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gold_low.setObjectName("label_gold_low")
        self.horizontalLayout_7.addWidget(self.label_gold_low)
        self.label_gold_high = QtWidgets.QLabel(self.widget)
        self.label_gold_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gold_high.setObjectName("label_gold_high")
        self.horizontalLayout_7.addWidget(self.label_gold_high)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_yen = QtWidgets.QLabel(self.widget)
        self.label_yen.setObjectName("label_yen")
        self.horizontalLayout_6.addWidget(self.label_yen)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.label_yen_low = QtWidgets.QLabel(self.widget)
        self.label_yen_low.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yen_low.setObjectName("label_yen_low")
        self.horizontalLayout_6.addWidget(self.label_yen_low)
        self.label_yen_high = QtWidgets.QLabel(self.widget)
        self.label_yen_high.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yen_high.setObjectName("label_yen_high")
        self.horizontalLayout_6.addWidget(self.label_yen_high)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/로그인.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLogin.setIcon(icon1)
        self.actionLogin.setStatusTip("")
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/로그아웃.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLogout.setIcon(icon2)
        self.actionLogout.setStatusTip("")
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/종료.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setStatusTip("")
        self.actionExit.setObjectName("actionExit")
        self.actionAccountDialog = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Resources/계좌조회.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAccountDialog.setIcon(icon4)
        self.actionAccountDialog.setObjectName("actionAccountDialog")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Resources/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersion.setIcon(icon5)
        self.actionVersion.setObjectName("actionVersion")
        self.actionScoreBoard = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Resources/전광판.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScoreBoard.setIcon(icon6)
        self.actionScoreBoard.setObjectName("actionScoreBoard")
        self.actionBigChart = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Resources/bigchart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBigChart.setIcon(icon7)
        self.actionBigChart.setObjectName("actionBigChart")
        self.action_ToolBar_BigChart = QtWidgets.QAction(MainWindow)
        self.action_ToolBar_BigChart.setCheckable(False)
        self.action_ToolBar_BigChart.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.action_ToolBar_BigChart.setFont(font)
        self.action_ToolBar_BigChart.setObjectName("action_ToolBar_BigChart")
        self.actionRealTimeItem = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Resources/설정.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealTimeItem.setIcon(icon8)
        self.actionRealTimeItem.setObjectName("actionRealTimeItem")
        self.action_ToolBar_RealTime_Setting = QtWidgets.QAction(MainWindow)
        self.action_ToolBar_RealTime_Setting.setIcon(icon8)
        self.action_ToolBar_RealTime_Setting.setObjectName("action_ToolBar_RealTime_Setting")
        self.action_ToolBar_ScoreBoard = QtWidgets.QAction(MainWindow)
        self.action_ToolBar_ScoreBoard.setIcon(icon6)
        self.action_ToolBar_ScoreBoard.setObjectName("action_ToolBar_ScoreBoard")
        self.menu.addAction(self.actionLogin)
        self.menu.addAction(self.actionLogout)
        self.menu.addAction(self.actionAccountDialog)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu.addSeparator()
        self.menu_3.addAction(self.actionVersion)
        self.menu_1.addAction(self.actionScoreBoard)
        self.menu_1.addAction(self.actionBigChart)
        self.menu_1.addSeparator()
        self.menu_2.addAction(self.actionRealTimeItem)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_ToolBar_ScoreBoard)
        self.toolBar.addAction(self.action_ToolBar_BigChart)
        self.toolBar.addAction(self.action_ToolBar_RealTime_Setting)

        self.retranslateUi(MainWindow)
        self.menubar.triggered['QAction*'].connect(MainWindow.MENU_Action)
        self.toolBar.actionTriggered['QAction*'].connect(MainWindow.TOOLBAR_Action)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skybot"))
        self.label_1st.setText(_translate("MainWindow", "TextLabel"))
        self.label_2nd.setText(_translate("MainWindow", "TextLabel"))
        self.label_3rd.setText(_translate("MainWindow", "TextLabel"))
        self.label_4th.setText(_translate("MainWindow", "TextLabel"))
        self.label_5th.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.groupBox_2.setTitle(_translate("MainWindow", "해외선물"))
        self.label_sp500.setText(_translate("MainWindow", "S&P 500"))
        self.label_sp500_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_sp500_high.setText(_translate("MainWindow", "TextLabel"))
        self.label_nasdaq.setText(_translate("MainWindow", "NASDAQ"))
        self.label_nasdaq_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_nasdaq_high.setText(_translate("MainWindow", "TextLabel"))
        self.label_wti.setText(_translate("MainWindow", "WTI"))
        self.label_wti_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_wti_high.setText(_translate("MainWindow", "TextLabel"))
        self.label_euro.setText(_translate("MainWindow", "EURO"))
        self.label_euro_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_euro_high.setText(_translate("MainWindow", "TextLabel"))
        self.label_dow.setText(_translate("MainWindow", "DOW"))
        self.label_dow_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_dow_high.setText(_translate("MainWindow", "TextLabel"))
        self.label_hsi.setText(_translate("MainWindow", "HSI"))
        self.label_hsi_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_hsi_high.setText(_translate("MainWindow", "TextLabel"))
        self.label_gold.setText(_translate("MainWindow", "GOLD"))
        self.label_gold_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_gold_high.setText(_translate("MainWindow", "TextLabel"))
        self.label_yen.setText(_translate("MainWindow", "YEN"))
        self.label_yen_low.setText(_translate("MainWindow", "TextLabel"))
        self.label_yen_high.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "세션"))
        self.menu_3.setTitle(_translate("MainWindow", "도움말"))
        self.menu_1.setTitle(_translate("MainWindow", "선물옵션"))
        self.menu_2.setTitle(_translate("MainWindow", "설정"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLogin.setText(_translate("MainWindow", "로그인"))
        self.actionLogout.setText(_translate("MainWindow", "로그아웃"))
        self.actionExit.setText(_translate("MainWindow", "종료"))
        self.actionAccountDialog.setText(_translate("MainWindow", "계좌조회"))
        self.actionVersion.setText(_translate("MainWindow", "버전"))
        self.actionScoreBoard.setText(_translate("MainWindow", "전광판"))
        self.actionBigChart.setText(_translate("MainWindow", "Big Chart"))
        self.action_ToolBar_BigChart.setText(_translate("MainWindow", "Big Chart"))
        self.action_ToolBar_BigChart.setToolTip(_translate("MainWindow", "Big Chart"))
        self.actionRealTimeItem.setText(_translate("MainWindow", "실시간요청"))
        self.action_ToolBar_RealTime_Setting.setText(_translate("MainWindow", "실시간요청 설정"))
        self.action_ToolBar_ScoreBoard.setText(_translate("MainWindow", "전광판"))
        self.action_ToolBar_ScoreBoard.setToolTip(_translate("MainWindow", "전광판"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
