# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skybot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 880)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/skybot_cm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 6, 622, 411))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 28, 595, 369))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1st = QtWidgets.QLabel(self.layoutWidget)
        self.label_1st.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1st.setObjectName("label_1st")
        self.verticalLayout.addWidget(self.label_1st)
        self.label_2nd = QtWidgets.QLabel(self.layoutWidget)
        self.label_2nd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2nd.setObjectName("label_2nd")
        self.verticalLayout.addWidget(self.label_2nd)
        self.label_3rd = QtWidgets.QLabel(self.layoutWidget)
        self.label_3rd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3rd.setObjectName("label_3rd")
        self.verticalLayout.addWidget(self.label_3rd)
        self.label_4th = QtWidgets.QLabel(self.layoutWidget)
        self.label_4th.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4th.setObjectName("label_4th")
        self.verticalLayout.addWidget(self.label_4th)
        self.label_5th = QtWidgets.QLabel(self.layoutWidget)
        self.label_5th.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5th.setObjectName("label_5th")
        self.verticalLayout.addWidget(self.label_5th)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout.addWidget(self.pushButton_reset)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(8, 428, 623, 369))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_cme = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_cme.setGeometry(QtCore.QRect(13, 30, 597, 327))
        self.tableWidget_cme.setObjectName("tableWidget_cme")
        self.tableWidget_cme.setColumnCount(0)
        self.tableWidget_cme.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/로그인.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLogin.setIcon(icon1)
        self.actionLogin.setStatusTip("")
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/로그아웃.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLogout.setIcon(icon2)
        self.actionLogout.setStatusTip("")
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/종료.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setStatusTip("")
        self.actionExit.setObjectName("actionExit")
        self.actionAccountDialog = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Resources/계좌조회.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAccountDialog.setIcon(icon4)
        self.actionAccountDialog.setObjectName("actionAccountDialog")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Resources/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersion.setIcon(icon5)
        self.actionVersion.setObjectName("actionVersion")
        self.actionScoreBoard = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Resources/전광판.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScoreBoard.setIcon(icon6)
        self.actionScoreBoard.setObjectName("actionScoreBoard")
        self.actionBigChart = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Resources/bigchart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBigChart.setIcon(icon7)
        self.actionBigChart.setObjectName("actionBigChart")
        self.action_ToolBar_BigChart = QtWidgets.QAction(MainWindow)
        self.action_ToolBar_BigChart.setCheckable(False)
        self.action_ToolBar_BigChart.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.action_ToolBar_BigChart.setFont(font)
        self.action_ToolBar_BigChart.setObjectName("action_ToolBar_BigChart")
        self.actionRealTimeItem = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Resources/설정.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRealTimeItem.setIcon(icon8)
        self.actionRealTimeItem.setObjectName("actionRealTimeItem")
        self.action_ToolBar_RealTime_Setting = QtWidgets.QAction(MainWindow)
        self.action_ToolBar_RealTime_Setting.setIcon(icon8)
        self.action_ToolBar_RealTime_Setting.setObjectName("action_ToolBar_RealTime_Setting")
        self.action_ToolBar_ScoreBoard = QtWidgets.QAction(MainWindow)
        self.action_ToolBar_ScoreBoard.setIcon(icon6)
        self.action_ToolBar_ScoreBoard.setObjectName("action_ToolBar_ScoreBoard")
        self.menu.addAction(self.actionLogin)
        self.menu.addAction(self.actionLogout)
        self.menu.addAction(self.actionAccountDialog)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu.addSeparator()
        self.menu_3.addAction(self.actionVersion)
        self.menu_1.addAction(self.actionScoreBoard)
        self.menu_1.addAction(self.actionBigChart)
        self.menu_1.addSeparator()
        self.menu_2.addAction(self.actionRealTimeItem)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_ToolBar_ScoreBoard)
        self.toolBar.addAction(self.action_ToolBar_BigChart)
        self.toolBar.addAction(self.action_ToolBar_RealTime_Setting)

        self.retranslateUi(MainWindow)
        self.menubar.triggered['QAction*'].connect(MainWindow.MENU_Action)
        self.toolBar.actionTriggered['QAction*'].connect(MainWindow.TOOLBAR_Action)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skybot"))
        self.label_1st.setText(_translate("MainWindow", "TextLabel"))
        self.label_2nd.setText(_translate("MainWindow", "TextLabel"))
        self.label_3rd.setText(_translate("MainWindow", "TextLabel"))
        self.label_4th.setText(_translate("MainWindow", "TextLabel"))
        self.label_5th.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.groupBox_2.setTitle(_translate("MainWindow", "해외선물"))
        self.menu.setTitle(_translate("MainWindow", "세션"))
        self.menu_3.setTitle(_translate("MainWindow", "도움말"))
        self.menu_1.setTitle(_translate("MainWindow", "선물옵션"))
        self.menu_2.setTitle(_translate("MainWindow", "설정"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLogin.setText(_translate("MainWindow", "로그인"))
        self.actionLogout.setText(_translate("MainWindow", "로그아웃"))
        self.actionExit.setText(_translate("MainWindow", "종료"))
        self.actionAccountDialog.setText(_translate("MainWindow", "계좌조회"))
        self.actionVersion.setText(_translate("MainWindow", "버전"))
        self.actionScoreBoard.setText(_translate("MainWindow", "전광판"))
        self.actionBigChart.setText(_translate("MainWindow", "Big Chart"))
        self.action_ToolBar_BigChart.setText(_translate("MainWindow", "Big Chart"))
        self.action_ToolBar_BigChart.setToolTip(_translate("MainWindow", "Big Chart"))
        self.actionRealTimeItem.setText(_translate("MainWindow", "실시간요청"))
        self.action_ToolBar_RealTime_Setting.setText(_translate("MainWindow", "실시간요청 설정"))
        self.action_ToolBar_ScoreBoard.setText(_translate("MainWindow", "전광판"))
        self.action_ToolBar_ScoreBoard.setToolTip(_translate("MainWindow", "전광판"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

