BEGIN_FUNCTION_MAP
	.Func,해외선물마스터조회(o3101)-API용,o3101,attr,block,headtype=A;
	BEGIN_DATA_MAP
	o3101InBlock,기본입력,input;
	begin
		입력구분(예비),gubun,gubun,char,1;
	end
	o3101OutBlock,출력-마스터,output,occurs;
	begin
		종목코드,Symbol,Symbol,char,8;
		종목명,SymbolNm,SymbolNm,char,50;
		종목배치수신일(한국일자),ApplDate,ApplDate,char,8;
		기초상품코드,BscGdsCd,BscGdsCd,char,10;
		기초상품명,BscGdsNm,BscGdsNm,char,40;
		거래소코드,ExchCd,ExchCd,char,10;
		거래소명,ExchNm,ExchNm,char,40;
		기준통화코드,CrncyCd,CrncyCd,char,3;
		진법구분코드,NotaCd,NotaCd,char,3;
		호가단위가격,UntPrc,UntPrc,double,15.8;
		최소가격변동금액,MnChgAmt,MnChgAmt,double,15.8;
		가격조정계수,RgltFctr,RgltFctr,double,15.10;
		계약당금액,CtrtPrAmt,CtrtPrAmt,double,15.2;
		상품구분코드,GdsCd,GdsCd,char,3;
		월물(년),LstngYr,LstngYr,char,4;
		월물(월),LstngM,LstngM,char,1;
		정산가격,EcPrc,EcPrc,double,15.8;
		거래시작시간,DlStrtTm,DlStrtTm,char,6;
		거래종료시간,DlEndTm,DlEndTm,char,6;
		거래가능구분코드,DlPsblCd,DlPsblCd,char,1;
		증거금징수구분코드,MgnCltCd,MgnCltCd,char,1;
		개시증거금,OpngMgn,OpngMgn,double,15.2;
		유지증거금,MntncMgn,MntncMgn,double,15.2;
		개시증거금율,OpngMgnR,OpngMgnR,double,7.3;
		유지증거금율,MntncMgnR,MntncMgnR,double,7.3;
		유효소수점자리수,DotGb,DotGb,long,2;
	end
	END_DATA_MAP
END_FUNCTION_MAP

